### ISSUE TITLE
redis-nvml with multithreading I/O support

### ISSUE THREAD

**Issue by jiawen11** [pmem/redis#218]
Hi experts,

The current redis-nvml is based on v3.2 and it does not support the multithreading I/O that is the new feature introduced since redis 6 (e.g., 1. https://www.i-programmer.info/news/197-data-mining/13682-redis-6-adds-multithreading-io.html; 
2. https://www.infoworld.com/article/3541356/redis-6-arrives-with-multithreading-for-faster-io.html#:~:text=With%20I%2FO%20threading%20enabled,a%20single%20instance%2C%20say%20creators&text=Redis%206%2C%20the%20newest%20version,moved%20to%20general%20availability%20today.)

Is there any open-source redis-nvml version that supports the multithreading I/O feature? Or is there any ongoing plan to support the multithreading I/O feature in redis-nvml?

Thanks!

**Comment by jschmieg** [comment]
Hello,
There is the Memkeydb project.
It uses PMEM in a volatile way as a DRAM extension. 
It is ported to many versions of Redis including version 6.x and supports all its features including multi-IO.
[memkeydb repository](https://github.com/memKeyDB/memKeyDB/tree/6.0.9-devel)

Best regards

**Comment by jiawen11** [comment]
Thanks!
